"""Bounded, offline-testable DailyMed connector and parsers."""

from .client import DailyMedConnector, DailyMedConnectorResult, RawDailyMedResponse
from .parsing import (
    DailyMedCandidatePage,
    DailyMedCandidateRecord,
    DailyMedHistoryPage,
    DailyMedHistoryRecord,
    DailyMedParseError,
    ParsedSplDocument,
    ParsedSplSection,
    parse_candidate_page,
    parse_historical_zip,
    parse_history_page,
    parse_spl_document,
)
from .policy import (
    DailyMedConnectorConfig,
    DailyMedFailure,
    DailyMedFailureKind,
    DailyMedOperation,
    DailyMedRequest,
    RetryEvent,
    build_dailymed_request,
    validate_connector_config,
    validate_dailymed_request,
    validate_setid,
    validate_spl_version,
)

__all__ = [
    "DailyMedCandidatePage",
    "DailyMedCandidateRecord",
    "DailyMedConnector",
    "DailyMedConnectorConfig",
    "DailyMedConnectorResult",
    "DailyMedFailure",
    "DailyMedFailureKind",
    "DailyMedHistoryPage",
    "DailyMedHistoryRecord",
    "DailyMedOperation",
    "DailyMedParseError",
    "DailyMedRequest",
    "ParsedSplDocument",
    "ParsedSplSection",
    "RawDailyMedResponse",
    "RetryEvent",
    "build_dailymed_request",
    "parse_candidate_page",
    "parse_historical_zip",
    "parse_history_page",
    "parse_spl_document",
    "validate_connector_config",
    "validate_dailymed_request",
    "validate_setid",
    "validate_spl_version",
]
